name: cicd-workflow
on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          format: 'table'
          scan-type: 'fs'
          exit-code: '1'
          severity: 'CRITICAL' # trivy ok... low 0, med 7, high 5, crit 0
          output: 'trivy-report.txt'

      - name: Upload Vuln Scan to Slack
        if: failure()
        uses: MeilCli/slack-upload-file@v4
        with:
            slack_token: ${{ secrets.PRIVATE_BOT_TOKEN }}
            channel_id: ${{ secrets.PRIVATE_SLACK_CHANNEL_ID }}
            file_path: 'trivy-report.txt'
            initial_comment: 'Scan report by Kei Yam'

      - name: Slack Notification with RTCamp
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.PRIVATE_SUBMISSION_URL }}
            SLACK_MESSAGE: >
                Name: Kei Yam\n
                Matriculation: A0291912A\n
                Email: keiyamx@gmail.com\n
                Git: https://github.com/Arabasta/cicd\n
                Image: Docker image link'

    #         SLACK_WEBHOOK_URL: ${{ secrets.PRIVATE_SUBMISSION_URL }}
    #         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
