name: cicd-workflow
on: 
    push:
        
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout source
          uses: actions/checkout@v2

        - name: Slack notification
          id: slack
          uses: slackapi/slack-github-action@v1.26.0
          with:
            payload: |
              {
                "text": "${{ github.event.head_commit.url }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "test pass"
                    }
                  }
                ]
              }
          env: 
            #SLACK_BOT_TOKEN: ${{ secrets.PRIVATE_BOT_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.PRIVATE_SUBMISSION_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK



