name: cicd-workflow
on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

        # Trivy
      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          format: 'table'
          scan-type: 'fs'
          exit-code: '1'
          severity: 'CRITICAL' # set 'HIGH' to test failure
          output: 'trivy-report.txt'

      - name: Upload Vuln Scan to Slack
        if: failure()
        uses: MeilCli/slack-upload-file@v4
        with:
            slack_token: ${{ secrets.PRIVATE_BOT_TOKEN }}
            channel_id: ${{ secrets.PRIVATE_SLACK_CHANNEL_ID }}
            file_path: 'trivy-report.txt'
            initial_comment: 'Scan report by Kei Yam'

      - name: Slack Notification with RTCamp
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.PRIVATE_SUBMISSION_URL }}
            SLACKIFY_MARKDOWN: true
            SLACK_TITLE: >
                **Scan failed - Kei Yam**
            SLACK_MESSAGE: >
                Failed trivy scan, see uploaded report

        # Docker
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
            push: true
            tags: keiyam/go-fortune:${{ github.sha }}


        # Slack
      - name: Slack Notification with RTCamp
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.PRIVATE_SUBMISSION_URL }}
            SLACKIFY_MARKDOWN: true
            SLACK_TITLE: >
                **Image build and signed**
            SLACK_MESSAGE: >
                **Name**: Kei Yam\n
                **Matriculation**: A0291912A\n
                **Email**: keiyamx@gmail.com\n
                **Git**: https://github.com/Arabasta/cicd
                \n**Image**: https://hub.docker.com/r/keiyam/go-fortune/
